spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin_cvs
    password: pwforcvsadmin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO

jwt:
  token:
    header: Authorization
    issuer: alliex
    clientId: cvs-jwt-app
    clientSecret: cvs-jwt-secret
    expirySeconds: 7200

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/db_cvs?serverTimezone=UTC&characterEncoding=UTF-8
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---
spring:
  profiles: ci
  datasource:
    url: jdbc:mysql://192.168.0.95:3306/db_cvs_ci?serverTimezone=UTC&characterEncoding=UTF-8

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.0.95:3306/db_cvs?serverTimezone=UTC&characterEncoding=UTF-8
logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/db_cvs?serverTimezone=UTC&characterEncoding=UTF-8
logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
