version: '3.1'

services:
  db:
    container_name: mariadb
    image: mariadb:10.5.4
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: pwForRoot
      TZ: Asia/Seoul

