### Authorization by token, part 1. Retrieve and save token.
POST http://{{host}}:{{port}}/api/login
content-type: application/json

{
  "username": "test",
  "password": "test"
}

> {% client.global.set("auth_token", response.body.token); %}

### Authorization by token, part 2. Use token to authorize.
GET http://{{host}}:{{port}}/api/v1/posts
content-type: application/json
Authorization: Bearer {{auth_token}}

### 충전 요청
POST http://{{host}}:{{port}}/api/v1/point/history/save
content-type: application/json
Authorization: Bearer {{auth_token}}

{
  "point": 100,
  "userId": 3
}
