### Login
POST http://localhost:8080/api/login
content-type: application/json

{
  "username": "test",
  "password": "test"
}

### Test Token
GET http://localhost:8080/api/v1/posts
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJhbGxpZXgiLCJuYmYiOjE2MTAwODcwMzcsImV4cCI6MTYxMDA5NDIzNywiaWF0IjoxNjEwMDg3MDM3LCJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9VU0VSIn1dLCJ1c2VybmFtZSI6InRlc3QifQ.axPKAYhav7Pu0wCwKa0LiCqYcpeoyz7YYLpMt5-9aAD_OvoYci4k677slG78nfnGaB91KyvG80lMK_p31jqKEQ

### 충전 요청
POST http://localhost:8080/api/v1/point/history/save
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJhbGxpZXgiLCJuYmYiOjE2MTAwODcwMzcsImV4cCI6MTYxMDA5NDIzNywiaWF0IjoxNjEwMDg3MDM3LCJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9VU0VSIn1dLCJ1c2VybmFtZSI6InRlc3QifQ.axPKAYhav7Pu0wCwKa0LiCqYcpeoyz7YYLpMt5-9aAD_OvoYci4k677slG78nfnGaB91KyvG80lMK_p31jqKEQ

{
  "point": 100,
  "userId": 3
}